server:
  port: ${server_port:0}
spring:
  application:
    name: guestbook-backend
eureka:
  client:
    serviceUrl:
      defaultZone: http://guestbook-discovery:8761/eureka/
  instance:
    instance-id: ${random.value}

hystrix:
  command:
    default:
      exeution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream