server:
  port: 8000
spring:
  application:
    name: guestbook-proxy
  zipkin:
    base-url: http://guestbook-zipkin:9411
  sleuth:
    sampler:
      probability: 1
zuul:
  routes:
    backend:
      path: /guestbook/**
      serviceId: guestbook-backend
      strip-prefix: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://guestbook-discovery:8761/eureka/
  instance:
    instance-id: ${random.value}
